"""
report_generator.py — Generates downloadable reports in Markdown and PDF formats.

Reports are designed to be submitted to:
  - cybercrime.gov.in (National Cyber Crime Reporting Portal)
  - CyberTipline (NCMEC-style)
  - Special Juvenile Police Unit (SJPU)

No harmful content is included in the report — only metadata, warning indicators,
and legal references are captured.
"""

from __future__ import annotations
import datetime
from analyzer import AnalysisResult


def generate_markdown_report(result: AnalysisResult, reporter_context: str = "") -> str:
    """
    Generate a CyberTipline-style incident report in Markdown format.
    Safe to share — does NOT include the original input text.
    """
    now = datetime.datetime.now()
    timestamp = now.strftime("%d %B %Y, %H:%M IST")
    report_id = now.strftime("RPT-%Y%m%d-%H%M%S")

    risk_emoji = {
        "Low": "🟢",
        "Medium": "🟡",
        "High": "🟠",
        "Critical": "🔴",
    }.get(result.risk_level, "⚪")

    lines = [
        "# CHILD ONLINE SAFETY INCIDENT REPORT",
        "",
        f"**Report ID:** `{report_id}`",
        f"**Generated:** {timestamp}",
        f"**Tool:** Child Online Safety Monitor (COSM) — Phantom Rizzlers / IBM Bob Hackathon",
        "",
        "---",
        "",
        "## ⚠️ IMPORTANT NOTICE",
        "",
        "> This report was generated from **metadata and pattern analysis only**.",
        "> The original content has NOT been reproduced here to prevent re-exposure.",
        "> Do NOT re-open, view, or share the original content.",
        "",
        "---",
        "",
        "## 1. RISK ASSESSMENT",
        "",
        f"| Field | Value |",
        f"|-------|-------|",
        f"| **Risk Level** | {risk_emoji} **{result.risk_level}** |",
        f"| **Risk Score** | {result.risk_score} / 100 |",
        f"| **Input Type** | {result.input_type.capitalize()} |",
        f"| **Warning Signs Detected** | {len(result.warning_signs)} |",
        "",
        "### Summary",
        "",
        result.summary,
        "",
        "---",
        "",
        "## 2. GROOMING WARNING SIGNS DETECTED",
        "",
    ]

    if result.warning_signs:
        for i, sign in enumerate(result.warning_signs, 1):
            lines += [
                f"### {i}. {sign.sign}",
                f"- **Category:** {sign.category.capitalize()}",
                f"- **Explanation:** {sign.explanation}",
                "",
            ]
    else:
        lines += ["No significant grooming indicators detected.", ""]

    lines += [
        "---",
        "",
        "## 3. APPLICABLE LEGAL PROVISIONS",
        "",
    ]

    if result.legal_mappings:
        for lm in result.legal_mappings:
            lines += [
                f"### {lm.act} — {lm.section}",
                f"- **Description:** {lm.description}",
                f"- **Maximum Penalty:** {lm.max_penalty}",
                "",
            ]
    else:
        lines += ["No specific legal provisions flagged at this risk level.", ""]

    lines += [
        "---",
        "",
        "## 4. EVIDENCE PRESERVATION CHECKLIST",
        "",
        "> Follow these steps IN ORDER. Do NOT skip Step 1.",
        "",
    ]

    for step in result.preservation_steps:
        lines.append(f"- {step}")

    lines += [
        "",
        "---",
        "",
        "## 5. REPORTING CONTACTS",
        "",
        "| Resource | Details |",
        "|----------|---------|",
        "| **National Cyber Crime Portal** | [cybercrime.gov.in](https://cybercrime.gov.in) |",
        "| **National Cyber Helpline** | 1930 |",
        "| **Childline India** | 1098 (24×7) |",
        "| **Emergency** | 112 |",
        "| **NCMEC CyberTipline** | [missingkids.org/gethelpnow/cybertipline](https://www.missingkids.org/gethelpnow/cybertipline) |",
        "| **iReport Portal (INTERPOL)** | [icse.interpol.int](https://icse.interpol.int) |",
        "",
        "---",
        "",
        "## 6. REPORTER CONTEXT",
        "",
        reporter_context if reporter_context.strip() else "_No additional context provided._",
        "",
        "---",
        "",
        "*This report was auto-generated by the Child Online Safety Monitor (COSM).*",
        "*It is intended as a first-step aid — professional law enforcement investigation is required.*",
        "*Generated for IBM Bob Hackathon 2025 — Team Phantom Rizzlers.*",
    ]

    return "\n".join(lines)


def generate_pdf_bytes(markdown_text: str) -> bytes:
    """
    Convert markdown report to PDF bytes using reportlab.
    Falls back to encoded markdown if reportlab is unavailable.
    """
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm
        from reportlab.lib import colors
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable, Table, TableStyle
        from reportlab.lib.enums import TA_LEFT, TA_CENTER
        import io

        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=A4,
            rightMargin=2 * cm,
            leftMargin=2 * cm,
            topMargin=2 * cm,
            bottomMargin=2 * cm,
        )

        styles = getSampleStyleSheet()
        story = []

        # Custom styles
        title_style = ParagraphStyle("CTitle", parent=styles["Title"], fontSize=16, spaceAfter=6, textColor=colors.HexColor("#1f2328"))
        h2_style = ParagraphStyle("CH2", parent=styles["Heading2"], fontSize=12, spaceBefore=12, spaceAfter=4, textColor=colors.HexColor("#3b82d4"))
        h3_style = ParagraphStyle("CH3", parent=styles["Heading3"], fontSize=10, spaceBefore=8, spaceAfter=2, textColor=colors.HexColor("#1f2328"))
        body_style = ParagraphStyle("CBody", parent=styles["Normal"], fontSize=9, leading=14, spaceAfter=4)
        warning_style = ParagraphStyle("CWarn", parent=styles["Normal"], fontSize=9, leading=14, backColor=colors.HexColor("#fff8e1"), borderPadding=6)

        for line in markdown_text.split("\n"):
            stripped = line.strip()
            if not stripped:
                story.append(Spacer(1, 4))
                continue
            if stripped.startswith("# "):
                story.append(Paragraph(stripped[2:], title_style))
            elif stripped.startswith("## "):
                story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#e5e7eb")))
                story.append(Paragraph(stripped[3:], h2_style))
            elif stripped.startswith("### "):
                story.append(Paragraph(stripped[4:], h3_style))
            elif stripped.startswith("---"):
                story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#e5e7eb")))
            elif stripped.startswith("> "):
                story.append(Paragraph(stripped[2:], warning_style))
            elif stripped.startswith("- "):
                story.append(Paragraph(f"• {stripped[2:]}", body_style))
            elif stripped.startswith("**") or stripped.startswith("*"):
                clean = stripped.replace("**", "<b>", 1).replace("**", "</b>", 1)
                story.append(Paragraph(clean, body_style))
            elif stripped.startswith("|"):
                # skip table lines in PDF (already in markdown)
                pass
            else:
                story.append(Paragraph(stripped, body_style))

        doc.build(story)
        buffer.seek(0)
        return buffer.read()

    except ImportError:
        # Fallback: return UTF-8 encoded markdown as bytes
        return markdown_text.encode("utf-8")
